In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving HR_Analytics_Cleaned.csv to HR_Analytics_Cleaned.csv

In [3]:
df = pd.read_csv("HR_Analytics_Cleaned.csv")

Basic exploration

In [4]:
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1473 entries, 0 to 1472
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1473 non-null   object
 1   Age                       1473 non-null   int64
 2   AgeGroup                  1473 non-null   object
 3   Attrition                 1473 non-null   object
 4   BusinessTravel            1473 non-null   object
 5   DailyRate                 1473 non-null   int64
 6   Department                1473 non-null   object
 7   DistanceFromHome          1473 non-null   int64
 8   Education                 1473 non-null   int64
 9   EducationField            1473 non-null   object
 10  EmployeeNumber            1473 non-null   int64
 11  EnvironmentSatisfaction   1473 non-null   int64
 12  Gender                    1473 non-null   object
 13  HourlyRate                1473 non-null   int64
 14  JobInvolvement            1473 non-null   int64
 15  JobLevel                  1473 non-null   int64
 16  JobRole                   1473 non-null   object
 17  JobSatisfaction           1473 non-null   int64
 18  MaritalStatus             1473 non-null   object
 19  MonthlyIncome             1473 non-null   int64
 20  SalarySlab                1473 non-null   object
 21  MonthlyRate               1473 non-null   int64
 22  NumCompaniesWorked        1473 non-null   int64
 23  OverTime                  1473 non-null   object
 24  PercentSalaryHike         1473 non-null   int64
 25  PerformanceRating         1473 non-null   int64
 26  RelationshipSatisfaction  1473 non-null   int64
 27  StockOptionLevel          1473 non-null   int64
 28  TotalWorkingYears         1473 non-null   int64
 29  TrainingTimesLastYear     1473 non-null   int64
 30  WorkLifeBalance           1473 non-null   int64
 31  YearsAtCompany            1473 non-null   int64
 32  YearsInCurrentRole        1473 non-null   int64
 33  YearsSinceLastPromotion   1473 non-null   int64
 34  YearsWithCurrManager      1473 non-null   int64
dtypes: int64(24), object(11)
memory usage: 402.9+ KB

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

Key HR analysis

Total employees

In [5]:
df.shape[0]

1473

Attrition count

In [6]:
df['Attrition'].value_counts()

Attrition
No     1236
Yes     237
Name: count, dtype: int64

Attrition Rate

In [7]:
(df['Attrition']=='yes').mean()*100

np.float64(0.0)

Average Age

In [9]:
df['Age'].mean()

np.float64(36.917175831636115)

Average Salary

In [10]:
df['MonthlyIncome'].mean()

np.float64(6500.228784792939)

Department wise Attrition

In [13]:
dept_attrition = df[df['Attrition']=='Yes'].groupby('Department').size()
print(dept_attrition)

Department
Human Resources            12
Research & Development    133
Sales                      92
dtype: int64

Age Group Anlysis

In [14]:
age_attrition = df[df['Attrition']=='Yes'].groupby('AgeGroup').size()
print(age_attrition)

AgeGroup
18-25     44
26-35    116
36-45     43
46-55     26
55+        8
dtype: int64

Education Field Attrition

In [16]:
education_attrition = df[df['Attrition']=='Yes'].groupby('EducationField').size().sort_values(ascending=False)
print(education_attrition)

EducationField
Life Sciences       89
Medical             63
Marketing           35
Technical Degree    32
Other               11
Human Resources      7
dtype: int64

Overtime Impact

In [17]:
overtime_attrition = df[df['Attrition']=='Yes'].groupby('OverTime').size()
print(overtime_attrition)

OverTime
No     110
Yes    127
dtype: int64

Job satisfaction Anlysis

In [21]:
job_sat = (df[df['Attrition']=='Yes'].groupby('JobSatisfaction').size())
print(job_sat)

JobSatisfaction
1    66
2    46
3    73
4    52
dtype: int64

Salary Slab Analysis

In [22]:
salary_attrition = (df[df['Attrition']=='Yes'].groupby('SalarySlab').size())
print(salary_attrition)

SalarySlab
10k-15k     20
15k+         5
5k-10k      49
Upto 5k    163
dtype: int64